FROM openjdk:21-slim
COPY "./target/remodify-microservice-projectrequest.jar" "remodify-microservice-projectrequest.jar"
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "remodify-microservice-projectrequest.jar" ]